<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Pseudocode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pseudocode</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.note.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(For|Do|While|End While|If|End If|Then|Else|End For|End Module|Select|Case|End Function)\b</string>
			<key>name</key>
			<string>keyword.control.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Integer|Real|String|Boolean)\b</string>
			<key>name</key>
			<string>storage.type.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Constant|Ref)\b</string>
			<key>name</key>
			<string>storage.modifier.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|==|!=</string>
			<key>name</key>
			<string>keyword.operator.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Display|Input|Declare|Set|Call|Return)\b</string>
			<key>name</key>
			<string>keyword.other.pseudocode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(Module)\s+(?=[A-Za-z_][A-Za-z0-9_]*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.pseudocode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.pseudocode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.pseudocode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
					<key>contentName</key>
					<string>entity.name.function.pseudocode</string>
					<key>end</key>
					<string>(?![A-Za-z0-9_])</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.pseudocode</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.function.parameters.pseudocode</string>
					<key>end</key>
					<string>(?=\)\s*)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(Function)\s+(?=\w.*\s+)(?=[A-Za-z_][A-Za-z0-9_]*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.pseudocode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.pseudocode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.pseudocode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[A-Za-z_][A-Za-z0-9_]*)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.pseudocode</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.function.identifier.pseudocode</string>
					<key>end</key>
					<string>(\))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=\w.*\s*\w+\s*[A-Za-z_][A-Za-z0-9_]*\s*\()</string>
					<key>contentName</key>
					<string>meta.function.return-type.pseudocode</string>
					<key>end</key>
					<string>(?=[A-Za-z_][A-Za-z0-9_]*\s*\()</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(Integer|Real|String|Boolean)\b</string>
							<key>name</key>
							<string>storage.type.pseudocode</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pseudocode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(')</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pseudocode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.pseudocode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pseudocode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pseudocode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.pseudocode</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pseudocode</string>
	<key>uuid</key>
	<string>3010fe6c-ea8a-4acf-a7cd-ffc0cb29b832</string>
</dict>
</plist>
